server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.223.10.250:3306/my_blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 413902
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
